src/SymbolManager.cpp
src/SymbolTable.cpp
src/SymbolTable.h

There is not really an specific file extension because is the user of the assembler who give the filename. I used the extension names I found in the pasmo documentation and the man pages from Debian.

Add support for pasmo symbolic tables

---

build/main.mk

This fixes some compile errors appeared in recent versions of OSX reported in issue #57.

Use `-stdlib=libc++` in OSX to use C++11 standard libraries

---

build/package-darwin/Info.plist

1. Disable the dark theme for the debugger. It looks rather messed up when half of the UI elements are dark and the other is not. (The dark theme was introduced in macOS 10.14.)
Before:
After:
2. Enable retina support so that everything appears sharp rather than upscaled. I have not seen any issues caused by enabling this.
Before:
After:

MacOS visual updates

---

src/DebuggerForm.cpp
src/DebuggerForm.h

Currently floating widgets can get lost if they are behind other windows, at least on Windows, because the window manager doesn't include them on the taskbar or in the alt-tab window list.
This change adds a menu "Floating widgets" which lists all floating (undocked) widgets. Clicking on one will raise the widget to the front and focus it.
Since multiple HexViewer widgets can be created, a universally unique identifier has been added to its widget_id through Qt's QUuid.
An incremental counter might've been more efficient, but this was the easiest solution for me to achieve.
Uuids could perhaps also be created for the other widgets, if they also can also be spawned multiple times.
This is the first c++ code I've written, so apologies if I'm doing things in sub-optimal ways.
This change was …

Added a submenu to bring focus to floating widgets

---

build/detectsys.py
build/executils.py
build/gitdist.py
build/main.mk
build/msysutils.py
build/outpututils.py
build/version.py
build/version2code.py
build/win_resource.py

This changes all the places where Python is used in the build system to use Python3 instead of Python2. It's mostly changing the syntax of print and except, and one instance of specifying an encoding to subprocess.Popen so it's a text stream instead of a binary stream.

Move build system to Python3

---

src/DebuggerData.cpp
src/DebuggerForm.cpp
src/SymbolTable.cpp

binary searching breakpoints is much more efficient, since they are already ordered by address value.

using binary search in findBreakpoint() and insertBreakpoint()

---

src/DockableWidget.cpp
src/DockableWidget.h

This patch changes this:
into this:
When window decoration is active the inexperienced user doesn't know that the tool can be docked back into the dockable area by dragging it over the application window, since that feature only works if you drag the tool by its body (and not by the window decoration). With this patch, the tool can still be resized by the status bar at the bottom right corner. That is, if the tool's QSizePolicy is not (fixed, fixed).
This patch was not tested on windows or mac since I don't use them.

Remove window decorations of floating tools but still allow them to be resized.

---

src/BitMapViewer.cpp
src/BitMapViewer.h
src/DebuggerForm.cpp
src/DebuggerForm.h
src/DisasmViewer.cpp
src/DisasmViewer.h
src/TileViewer.cpp
src/TileViewer.h
src/VDPRegViewer.cpp
src/VDPRegViewer.h
src/VDPStatusRegViewer.cpp
src/VDPStatusRegViewer.h
src/VramBitMappedView.cpp
src/VramBitMappedView.h
src/VramTiledView.cpp
src/VramTiledView.h

Signals in Qt have passive voice form, so they use nouns+past tense verbs. And, since slots are just tagged methods, they follow the verb+object (or just verb) convention of functions and methods, unless the verb is "get", then it just vanishes in thin air (because this is not java).
**Warning:** This is not a comprehensive fix, since some signals and slots seem to follow some QtCreator name composition thing. Didn't want to touch that.

fixed some inconsistent name convention according to C++ and Qt rules

---

src/DisasmViewer.cpp

Bugfix: DisasmViewer::memoryUpdated needs to be aware of the OnDemand case.
Also, initialize variables disasmStart and disasmEnd. Thanks @grauw for discovering this and letting me know.

Added case OnDemand to DisasmViewer::memoryUpdated

---

src/CommClient.cpp
src/CommClient.h
src/ConnectDialog.h
src/DebuggerForm.cpp
src/DebuggerForm.h
src/OpenMSXConnection.cpp
src/OpenMSXConnection.h

This feature adds the power of lambda functions running on cascading events expressed as a simple inline. For instance, this is possible now:
```
CommClient::instance().sendCommand(new CascadingCommand("debug remove_bp bp#3",
[this] (const QString&) { emit breakpointsChanged(); },    // success
[this] (const QString& msg) { logError(msg); }             // fail
);
```
and it will run `emit breakpointsChanged();` if `debug remove_bp bp#3` command was successful or `logError(msg);` if it wasn't. Failing lambda function is optional and can be omitted. This feature requires C++11.

lambda functions parameters implemented as Command

---

.github/workflows/build.yaml
.gitignore
src/ConnectDialog.cpp
src/openmsx/SspiUtils.cpp
src/openmsx/SspiUtils.h

I created the file `.github/workflows/build.yaml` that compiles the project for GNU and Windows (currently no Mac binary is generated). Tests may be necessary since I don't own a windows box to test the generated package. But the GNU binary works if you have Qt 5.15 pre-installed and btw that's why its package is so small compared to the Windows one.
Some missing files were included in `src/openmsx`, like `MSXException.hh` and files it depends upon.

github workflow compiles windows and gnu binaries

---

src/BreakpointDialog.cpp
src/BreakpointDialog.h
src/DebuggerData.cpp
src/DebuggerData.h
src/DebuggerForm.cpp
src/DebuggerForm.h
src/HexViewer.cpp
src/SlotViewer.cpp

`MemoryLayout` constructor has code such as:
```
primarySlot[p] = '0';
secondarySlot[p] = 'X';
```
which tells me that they store ASCII code. But then, everywhere else `MemoryLayout::{primary, secondary}Slot` are treated as byte-sized integers. This is confusing and error prone. I am surprised it didn't burst into flames when I found it, since there are loads of code that do this:
```
if (bp.ps == -1 || bp.ps == memLayout->primarySlot[page])
...
if (bp.ss == -1 || bp.ss == memLayout->secondarySlot[page])
```
but then I found later on that `SlotViewer::slotsUpdated()` sets `MemoryLayout::{primary, secondary}Slot` as byte-sized integers as well after the first debug step:
```
memLayout->primarySlot  [p] = lines[p * 2][0].toLatin1()-'0';
memLayout->secondarySlot[p] = lines[p * …
```

MemoryLayout constructor changes

---

.github/workflows/build.yaml

force push is common procedure when pull requesting, since not all code changes are additive (some things need to be rewritten and a polluted history is no fun). Pull requests are the right time to do force pushes since you shouldn't rebase your master branch anyway. This change allows github actions to perform compilation checks after force pushes too.

github action should rerun checks after force push

---

src/DebuggerData.cpp

failed `std::find` could leave `bp.type` in an invalid or old state.

fix load session when breakpoint type is invalid

---

.github/workflows/release.yaml

Made a mistake with the `if` condition and I thought it was GitHub misbehaving. Sorry.

if condition was not working

---

build/main.mk
src/BreakpointDialog.cpp
src/BreakpointDialog.h
src/BreakpointViewer.cpp
src/BreakpointViewer.h
src/BreakpointViewer.ui
src/CPURegsViewer.h
src/DebuggerData.cpp
src/DebuggerData.h
src/DebuggerForm.cpp
src/DebuggerForm.h
src/DisasmViewer.h
src/DockableWidget.cpp
src/DockableWidget.h
src/DockableWidgetArea.h
src/DockableWidgetLayout.h
src/FlagsViewer.h
src/ScopedAssign.h
src/SlotViewer.cpp
src/SlotViewer.h
src/StackViewer.h
src/node.mk

A table of breakpoints that is separated from DisasmView makes breakpoints easier to manage.
TODO:
* ~fix update issues~
* ~fix widget style properties~
* ~primary field~
* ~secondary field~
* ~join primary and secondary fields~
* ~segment field~
* ~watchpoint table~

new widget: table of breakpoints (BreakpointViewer)

---

src/DebuggerForm.cpp
src/DockableWidget.cpp

Definitive fix for tools getting behind main window, specially if they were created first in a docked state and later became floaters. This is practically a part 2 of pull request #83.
Also: some tools were not closing when main window was closed because they are set to not destruct and `event->ignore()`'ing close events, which interrupts the process of application shutdown and let them in a weird zombie state.
So now we `hide()` all of them individually when closing the main window. That seems to do the trick.

no tools left behind... the main window

---

src/DisasmViewer.cpp

When the window is maximized on a vertical screen (portrait view), the value of `visibleLines` may be greater than `disasmLines.size()`, so `disasmTopLine` can become negative. Changing `std::min` and `std::max` order will make sure that `disasmTopLine` remains non negative.

crash if maximized in vertically rotated monitor

---

src/BreakpointViewer.cpp
src/BreakpointViewer.h
src/BreakpointViewer.ui
src/DebuggerData.cpp
src/DebuggerForm.cpp

`BreakpointViewer` now stores references to Breakpoints (Breakpoint, Watchpoints and Conditions) through 3 `std::map`s of new data structure `BreakpointData` because just storing references in a hidden column in `QTableWidget` is not flexible or powerful enough. The new data structure allows `BreakpointViewer` to sync with the emulator only when reconnected and not every time a new breakpoint is created or modified, which is more efficient. Also, since the table of breakpoints is not erased every time, items will not move around without the user's consent (they will not be destroyed and recreated, but reused).
minor changes:
* renamed `processXXXX` functions to `parseXXXX` because it is a less generic name;
* hidden 6th table column stores breakpoint name (id) instead of index;
* more …

BreakpointViewer doesn't reload breakpoints anymore

---

src/SlotViewer.cpp

...and  (`SlotViewer::updateSlots()` was just subtracting **0** to get an integer, but **X** is a common answer for secondary slot). Also `memLayout->isSubslotted[p]` cannot be used since it is outdated. The new status is the one read from `DebugMemMapperHandler`.
* `slotsUpdated` signal was always being emitted, but it should be emitted only when slots, subslots and segment actually change values.
This should've been fixed in #92, but we missed the spot.

secondary slot being misinterpreted in SlotViewer

---

.github/workflows/nightly.yaml

* It's no longer necessary to be logged in to access the pre-compiled debugger;
* It is also easier to find it in the **Releases** side menu link on the GitHub repository page;
* The nightly build will not be deleted automatically after 90 days, unlike the pull request artifacts;
* Last push to the repository will automatically delete the previous nightly build and replace it with the new one;
* Failed compilations will not delete nor replace the previous nightly build;
This is how it looks like: https://github.com/pvmm/debugger/releases

Github action publishes nightly build

---

src/BreakpointViewer.cpp
src/BreakpointViewer.h
src/BreakpointViewer.ui
src/DebuggerForm.cpp

In BreakpointViewer:
* `BreakpointData` renamed to `BreakpointRef` because it is a less generic name;
* Improved breakpoint matching by similarity tries to minimize **QTableWidget** item duplication when sync'ing and populating the tables;
* minor code reuse optimizations;
Other stuff:
* removing connection between `DebuggerForm::connected` and `BreakpointViwer::sync` which has no effect since no breakpoint has been processed yet (`reloadBreakpoints` has not been called yet);

Searching QTableWidget elements by similarity

---

src/BreakpointDialog.cpp
src/BreakpointDialog.h
src/BreakpointViewer.cpp
src/BreakpointViewer.h
src/Convert.cpp
src/Convert.h
src/DebuggerData.cpp
src/DebuggerData.h
src/DebuggerForm.cpp
src/DebuggerForm.h
src/GotoDialog.cpp
src/GotoDialog.h
src/MainMemoryViewer.cpp
src/SpriteViewer.cpp
src/SymbolManager.cpp
src/TileViewer.cpp
src/VDPCommandRegViewer.cpp
src/VDPCommandRegViewer.h

* `make_positive_optional` (tentative name) function converts negative (interpreted in many places as invalid or generic value) into optional null.
* `createSetCommand` now uses `AddressRange` and `Slot` structs;
* `stringToValue` returns `optional<int>` because string may not be convertible;
* `BreakpointDialog` now returns `Slot` and `AddressRange` structs;
* `segment` should now fit in a `uint8_t`, since `-1` is not used anymore to mean any or no segment;
* `stringToValue` now has a parametric type (defaults to `int`) to avoid the 0xFFFF or 0xFF masks;
* rejects value when overflow is detected;
* `make_if` functions used to create optionals more easily;
* `Breakpoint::range` is optional because conditions don't use them.

using std::optional null instead of -1

---

src/BitMapViewer.cpp
src/BitMapViewer.h

Removing this warning:
```
Compiling BitMapViewer.cpp...
src/BitMapViewer.cpp: In constructor ‘BitMapViewer::BitMapViewer(QWidget*)’:
src/BitMapViewer.cpp:33:50: warning: ‘void QComboBox::currentIndexChanged(const QString&)’ is deprecated: Use currentIndexChanged(int) instead, and get the text using itemText(index) [-Wdeprecated-declarations]
33 |     connect(screenMode, qOverload<const QString&>(&QComboBox:: currentIndexChanged), this, &BitMapViewer::on_screenMode_currentIndexChanged);
|                         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

deprecated warnings

---

src/BitMapViewer.cpp
src/BitMapViewer.h
src/BitMapViewer.ui

This fix makes debugging less torturous since a "step" command will no longer reset "Show Page" to the active page when "Use current VDP settings" is not active. Also renamed "Show page" to "Current page" because it changes meaning when the VDP register are disabled.

Reset "Show page" only if "Use current VDP settings" is active

---

src/DebuggerForm.cpp
src/DebuggerForm.h
src/PreferencesDialog.cpp
src/PreferencesDialog.h
src/PreferencesDialog.ui
src/Settings.cpp
src/Settings.h
src/SymbolManager.cpp
src/SymbolManager.h
src/SymbolTable.cpp
tmp.ui

Allow the debugger to forget old symbols, because it tends to get saturated with old and invalid labels in the symbol table. This patch also creates an entry on the preferences dialog.

optionally preserve lost symbol

---

src/SymbolManager.cpp
src/SymbolManager.h
src/SymbolManager.ui

The contents of a symbol file can now be redirected to specific slot/subslot arrangement for better debugging experience. The `Destination segments` column doesn't work yet because the `Active segments` in the `Locations` group box doesn't do anything to begin with.

Allow user to redirect symbol file to slot/subslot

---

src/DebuggerForm.cpp
src/PreferencesDialog.cpp
src/PreferencesDialog.h
src/PreferencesDialog.ui
src/Settings.cpp
src/Settings.h

One less thing to interrupt the user when he is in a tight compile/debug cycle.

Make "Symbol file changed" dialog optional

---

src/SymbolManager.cpp
src/SymbolTable.cpp
src/SymbolTable.h

Having the Session Manager read OMDS files allows us to import symbols, breakpoints and watchpoints from other projects. You can, for instance, maintain an OMDS file containing only BIOS symbols for several different debugging sessions. And you will not need to adjust the symbol slots/subslots ever again.

Symbol Manager can read OMDS files without changing the session

---

src/VramTiledView.cpp

Wrong tile coordinate in TileViewer.

Reverting error on fa86112c06c790f936e9e68af17cdd1c5e06cb65

---

src/BitMapViewer.cpp
src/DebuggerForm.cpp

Also fixed the black screen when BitmapViewer opens for the first time. This was caused by using an empty palette from VDPDataStore.

refresh open BitmapViewer before connected

---

src/SymbolManager.cpp

show just file name in SymbolManager instead of full path

---

src/DockableWidget.cpp

On Mac OS, `Qt::Tool` without `Qt::WA_MacAlwaysShowToolWindow` has, for a lack of a better description, the effect of `AlwaysOnBottom` after the main window loses focus to another application.

Remove Qt::Tool from Mac OS floating widgets

---

src/DebuggerForm.cpp
src/TileViewer.cpp
src/VDPDataStore.cpp
src/VDPDataStore.h
src/VDPRegViewer.cpp
src/VDPRegViewer.h
src/VDPRegistersExplained.ui

Debbuger getting ready to use the latest changes in OpenMSX (https://github.com/openMSX/openMSX/pull/1486)

New debuggables

---

src/BitMapViewer.ui
src/SpriteViewer.ui
src/TileViewer.ui

BitmapViewer should open with "Edit Palette..." disabled by default because "Use VDP palette registers" is checked by default.

"Edit palette..." disabled by default

---

src/DebuggerForm.cpp

supporting feature from commit https://github.com/openMSX/openMSX/commit/cabc54edc9396a0b26d9de662933d8488ee04ac3
It falls back to default behaviour if DebugSession::debugUpdates is not true.

support openMSX feature update events for bp

---

src/BreakpointViewer.cpp
src/BreakpointViewer.h
src/DebuggerForm.cpp

This will allow BreakpointViewer to refresh automatically when a symbol file change is detected.
Also:
* BreakpointViewer: renamed sync to refresh to be more compliant with other widgets;
* selfUpdating renamed to disableRefresh;

connected symbolFilesChanged to BreakpointViewer

---

src/DebuggerForm.cpp

Connecting to OpenMSX (for the first time only) triggers `onSlotUpdated`, which automatically refreshes the `disasmView`. So it will update twice. But I think this is barely noticeable.
Removed `forceBreak` that is not used anywhere.
This fixes issue #21 partially.

partial fix issue #21: DisasmViewer always reload on connect

---

src/BitMapViewer.cpp
src/PaletteDialog.cpp
src/PaletteDialog.h
src/PaletteDialog.ui
src/TileViewer.cpp
src/VDPDataStore.cpp
src/VDPDataStore.h

Now the palette editor allows the user to restore palette to the default MSX palette. `Apply` is not as useful as the `Defaults` button, so it was removed to reduce clutter.

PaletteDialog: replace apply with restore defaults
